### ISSUE TITLE
Issue genérica(temas gerais)

### ISSUE THREAD

**Issue by l3n0nr** [lenonr/dev_web#10]
[FORMULARIO] - Mostrar usuarios que cadastraram a solicitação, diretamente no formulario para o avaliador.

[ANALISE SOLICITACAO] - Caso o usuario interrompa uma solicitação, abrir uma janela para cadastrar as medidas tomadas na mesma.

[CAIXA DE MENSAGEM PERSONALIZADA] - Desenvolver as mensagens para os usuarios de forma especifica, de acordo com a avaliação da demanda feita pelo avaliador.

[VERIFICAÇÃO NO EMAIL] - Enviar email para o usuario, antes de liberar acesso ao sistema. Campo verificação tabela usuario.

[CRIPTOGRAFIA DOS DADOS NO SISTEMA] - Criptograr senha do usuario do sistema, para maior segurança, além de informações trocadas entre formulários.

[VISUALIZAÇÃO DADOS ADMINISTRADOR] - Verificar consulta SQL, existe um erro nela o que causa um erro ao mostrar os dados das tabelas solicitadas.

**Comment by lenonr** [comment]
[TABELAS] - Tabelas revisadas e restruturadas.

**Comment by l3n0nr** [comment]
[USUARIO OUTROS] - Verificado e alterado para Professor;

[TABELAS] - Revisão realizada.

[BUSCA] - Para otimizar a implementação do sistema, essa opção será desenvolvida posteriormente.
